version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8084:8084
    volumes:
      - ./conf:/mosquitto/config
      - ./ssl:/mosquitto/certs
    user: 1000:1000
