version: '3'
services:
  db:
    image: mariadb:10.11
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"

  web:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
        - GROUPNAME = ${GROUPNAME}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    user: "${UID}:${GID}"
    volumes:
      - ./src:/home/${USERNAME}/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      DATABASE_PASSWORD: password
      TZ: "Asia/Tokyo"

volumes:
  mysql-data:
    driver: local
